[build]
	publish = "_site"
	command = "npm run build"

# redirect to english, japanese landing pages.

[[redirects]]
  from = "/"
  to = "/ja"
  status = 302
  force = true
  conditions = {Language = ["ja"]}

[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  force = true

# redirect the 404 pages to your specific variant.

[[redirects]]
  from = "/ja/*"
  to = "/ja/404"
  status = 404

[[redirects]]
  from = "/en/*"
  to = "/en/404"
  status = 404

[[plugins]]

	# Opt-in to the Netlify Lighthouse plugin (choose one):

	# 1. Go to your site on https://app.netlify.com and navigate to the Integrations tab, search for the `Lighthouse` plugin
	# 2. Or via `npm install -D @netlify/plugin-lighthouse`

	# Read more: https://github.com/netlify/netlify-plugin-lighthouse

	package = "@netlify/plugin-lighthouse"

	# optional, fails build when a category is below a threshold
	[plugins.inputs.thresholds]
		performance = 1.0
		accessibility = 1.0
		best-practices = 1.0
		seo = 1.0

	[plugins.inputs]
		output_path = "reports/lighthouse/index.html"
